- deployments/values/supported-matrix.yaml
> OPSEXP-2173 Bump compatibility matrix for andromeda releases

- deployments/uber-manifest.tpl
- deployments/values/supported-matrix.yaml
Ref: OPSEXP-2174
* support aca
* configure control center
* bump tengine version
> OPSEXP-2174 Fixup community docker compose support

- deployments/values/supported-matrix.yaml
> OPSEXP-2234 Update compatibility matrix for Aquarius release

- deployments/uber-manifest.tpl
> OPSEXP-2234 Make optional docker compose with share

- deployments/values/supported-matrix.yaml
> OPSEXP-2235 Avoid forgetting to update community

- deployments/uber-manifest.tpl
> OPSEXP-1908 Support updating appVersion in main template

- deployments/values/supported-matrix.yaml
> OPSEXP-2311 Bump compatibility matrix for Cassiopeia release

- deployments/uber-manifest.tpl
> OPSEXP-2364 Fixup deprecated warning in pipeline name

- deployments/uber-manifest.tpl
> OPSEXP-2364 Fixup failure when no compose for acs is present

- deployments/uber-manifest.tpl
> OPSEXP-2365 Fix empty compose transformer prefix

- deployments/values/supported-matrix.yaml
> OPSEXP-2365 Bump AI to v3 for last release

- deployments/values/supported-matrix.yaml
> OPSEXP-2365 Fixup tengine and community versions for 23.1

- deployments/values/supported-matrix.yaml
Tested in https://github.com/Alfresco/acs-deployment/pull/1047
Ref: OPSEXP-2403
> OPSEXP-2403 Pin exact search enterprise version for older releases

- deployments/uber-manifest.tpl
- deployments/values/supported-matrix.yaml
> OPSEXP-2462 Add current values in supported matrix for default values file. 

- deployments/values/supported-matrix.yaml
> OPSEXP-2465 Remove support for ACS 7.0 

- deployments/uber-manifest.tpl
- deployments/values/supported-matrix.yaml
> OPSEXP-2630 Support insight zeppelin in the supported matrix

- deployments/uber-manifest.tpl
> OPSEXP-2630 Support insight zeppelin appVersion

- deployments/values/supported-matrix.yaml
> OPSEXP-2677 Support version 7.3.2 acs version for Gemini release

- deployments/values/supported-matrix.yaml
> OPSEXP-2778 Bump search enterprise version in supported matrix

- deployments/values/supported-matrix.yaml
> OPSEXP-2778 Update frontend apps versions for Indus release

- deployments/values/supported-matrix.yaml
> OPSEXP-2871 Bump for Libra release

- deployments/uber-manifest.tpl
- deployments/values/supported-matrix.yaml
Tested with acs-deployment:
* https://github.com/Alfresco/acs-deployment/actions/runs/11913129699/job/33198179310
* https://github.com/Alfresco/acs-deployment/actions/runs/11912484906/job/33196171089
> OPSEXP-2890: Add ACS audit component to the supported matrix

- deployments/values/supported-matrix.yaml
> OPSEXP-2981: refresh connector versions in compat matrix

- deployments/values/supported-matrix.yaml
> OPSEXP-3034 Update versions for Pegasus release

- deployments/values/supported-matrix.yaml
> OPSEXP-3098 Switch to semver for acs 23 releases

- deployments/uber-manifest.tpl
- deployments/values/supported-matrix.yaml
OPSEXP-3167
tested in https://github.com/Alfresco/acs-deployment/actions/runs/13787510517
> OPSEXP-3167 Filter by regexp before filtering by semver

- deployments/values/supported-matrix.yaml
OPSEXP-3114
need to wait for the release to be complete before merging
> OPSEXP-3114 Bump matrix for v25

- deployments/values/supported-matrix.yaml
> OPSEXP-3157 Remove 7.2 support

- deployments/values/supported-matrix.yaml
> OPSEXP-3454 Bump versions for Vela release
