deployments/uber-manifest.tpl
deployments/values/supported-matrix.yaml

Ref: OPSEXP-2174
* Fixup tengine-aio that for some reason was missing
* Rename latest section to 7.4.N to uniform with the others
* support multiple target keys also for search enterprise compose

OPSEXP-2174 Support next development release

---

deployments/uber-manifest.tpl

Ref: OPSEXP-1861
Needed to integration updatecli pipelines in alfresco-helm-charts without breaking on missing compose files:
tested the resulting pipeline locally:
```bash
REPORTS:
✔ UBER-MANIFEST.TPL:
Source:
✔ [intelligenceTag_74n] Intelligence Service image tag
✔ [msteamsTag_74n] MS Teams Service image tag
✔ [onedriveTag_74n] Onedrive (OOI) Service image tag
✔ [searchEnterpriseTag_74n] Search Enterprise tag
✔ [searchTag_74n] Alfresco Search Services
✔ [sfsTag_74n] Alfresco Shared Filestore image tag
✔ [syncTag_74n] Sync Service image tag
✔ [tengine-imTag_74n] Alfresco ImageMagick Transform Engine image tag
✔ [tengine-loTag_74n] Alfresco LibreOffice Transform Engine image tag
✔ [tengine-miscTag_74n] Alfresco misc Transform Engine image tag
✔ [tengine-pdfTag_74n] Alfresco PDF Transform …
```

OPSEXP-1861: skip sfs & trouter compose if no matching keys in values

---

deployments/uber-manifest.tpl
deployments/values/supported-matrix.yaml

Ref: OPSEXP-2364
Tested in https://github.com/Alfresco/alfresco-helm-charts/pull/148

OPSEXP-2364 Bump supported matrix for acs 23.1 release

---

deployments/uber-manifest.tpl

Ref: OPSEXP-2364
Tested in https://github.com/Alfresco/alfresco-helm-charts/actions/runs/6786629358/job/18447581655

OPSEXP-2364 Fixup support of multiple helm keys in search chart

---

deployments/values/supported-matrix.yaml

Ref: OPSEXP-2365
It's the simpler workaround I can think of and didn't want to bother since those versions are going to get deprecated soon, but the root cause really is that we are using regexp filters because most tags are not really semver compliant, and quay is returning tags sorted by creation date, hence we get this weird behaviour.
When running updatecli workflow I get:

OPSEXP-2365 Workaround for older releases versions

---

deployments/values/supported-matrix.yaml

Ref: OPSEXP-2404
Tested in https://github.com/Alfresco/acs-deployment/pull/1051

OPSEXP-2404 Fixup ATS/Sync matrix for ACS 7.3, 7.2 to fix CVE-2023-46604

---

deployments/values/supported-matrix.yaml

OPSEXP-2403 Bump sync service matrix to fix CVE-2023-46604

---

deployments/values/supported-matrix.yaml

OPSEXP-2422 Bump intelligence for ACS 7.1 to fix CVE-2023-46604

---

deployments/uber-manifest.tpl
deployments/values/supported-matrix.yaml

OPSEXP-2444 Bump compatibility matrix for draco release

---

deployments/uber-manifest.tpl
deployments/values/supported-matrix.yaml

OPSEXP-2189 Automate updating of activemq in activemq chart

---

deployments/uber-manifest.tpl
deployments/values/supported-matrix.yaml

OPSEXP-2503 Add possibility to change activemq image registry. 

---

deployments/values/supported-matrix.yaml

OPSEXP-2519 Bump supported matrix for acs 23.2 release 

---

deployments/values/supported-matrix.yaml

OPSEXP-2630 Bump matrix for Fornax release

---

deployments/uber-manifest.tpl
deployments/values/supported-matrix.yaml

OPSEXP-2629 Bump ATS compatibility for ACS 7.4

---

deployments/values/supported-matrix.yaml

OPSEXP-2650 Update supported matrix for multiple acs versions with new adw/acc

---

deployments/values/supported-matrix.yaml

Ref: OPSEXP-2651
Latest repo images are still shipping 4.x sync AMP which is not compatible with 5.x sync

OPSEXP-2651 Revert sync service 5.x bump due to repo image update not released yet

---

deployments/values/supported-matrix.yaml

Ref: OPSEXP-2740
Tested in:
* https://github.com/Alfresco/alfresco-helm-charts/actions/runs/9875372847
* https://github.com/Alfresco/acs-deployment/actions/runs/9876222577

OPSEXP-2740: Bump supported matrix after Hydra release

---

deployments/values/supported-matrix.yaml

OPSEXP-2874 Bump Insight Engine to 2.0.12

---

deployments/uber-manifest.tpl
deployments/values/supported-matrix.yaml

Ref: OPSEXP-2694
Allow consumers to not specify helm variable (e.g. update docker compose files only)

OPSEXP-2694: allow more flexible uber manifest 

---

deployments/values/supported-matrix.yaml

OPSEXP-2938 Update supported matrix for Orion release

---

deployments/values/supported-matrix.yaml

OPSEXP-2981: Reflect ATS supported matrix in 7.2 & 7.3 ACS versions & retire 7.1

---

deployments/uber-manifest.tpl
deployments/values/supported-matrix.yaml

Ref: OPSEXP-2989
Tested in https://github.com/Alfresco/acs-deployment/actions/runs/12280455809/job/34266917155

OPSEXP-2989: move acs and share to semver for 'next' matrix

---

deployments/uber-manifest.tpl

Sometimes we don't need to evaluate sources for all the supported versions, a possible approach could be to set the `.id` filter to null/false and skip the entire version sources.

OPSEXP-3154 Skip sources when id is unset/falsy

---

deployments/uber-manifest.tpl

Ref: OPSEXP-3218
Because of: https://github.com/Alfresco/acs-deployment/pull/1300
Fix for: https://github.com/Alfresco/acs-deployment/pull/1357/commits/ee7267d479666e777d2883f5826cdbe844c404e3
tested on: https://github.com/Alfresco/acs-deployment/pull/1357/commits/7a4d35ba5df65c53901b868bbe60d800153a5c61

OPSEXP-3218 Make alfresco-transform-core-aio image configurable

---

deployments/values/supported-matrix.yaml

https://hyland.atlassian.net/browse/OPSEXP-3322
This PR will be merged after 7.3 support has been removed from acs-deployment

OPSEXP-3322: remove 7.3 from matrix
